name: publish

on:
  release:
    types: [published]

jobs:

  build:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: $( echo ghcr.io/${GITHUB_REPOSITORY} )
      IMAGE_VERSION: $( echo ${GITHUB_REF#"refs/tags/"} )

    steps:
      - uses: actions/checkout@v2

      - name: "Build the Docker image"
        run: docker build . --file Dockerfile --tag ${{ env.IMAGE_NAME }}:latest --tag ${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}

      - name: "Login to registry"
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: "Publish the Docker image"
        run: docker push -a ${{ env.IMAGE_NAME }}
